config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
	
	resources :images
	get 'upload' => 'images#new'

  devise_for :users, :controllers => { :registrations => 'registrations' }

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :user

	has_attached_file :data, :styles => { :thumb => "100x100#", :medium => "300x300#" }
	validates_attachment_content_type :data, :content_type => /\Aimage/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_attached_file :profile_picture, styles: { tiny: "35x35#", small: "100x100#", medium: "300x300#" }
	validates_attachment_content_type :profile_picture, :content_type => /\Aimage/

	has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
	
	before_filter :configure_devise_params, if: :devise_controller?
		def configure_devise_params
			devise_parameter_sanitizer.for(:edit) do |u|
				u.permit(:display_name, :profile_picture, :email, :password, :password_confirmation)
			end
		end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def new
		@image = Image.new
	end

	def create
		@image = Image.create(user_params)
		@image.user = current_user
		@image.save
	
		redirect_to root_path
	end
	
	def edit
	end
	
	def update
	end

	def destroy
	end

	def user_params
		params.require(:image).permit(:title, :data)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def account_update_params
		params.require(:user).permit(:display_name, :profile_picture, :email, :password, :password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/images/new.html.erb
<h1>Upload a new picture</h1>

<%= form_for @image, :url => images_path, :html => { :multipart => true } do |f| %>
	<% if @image.errors.any? %>
	<ul>
		<% @image.errors.full.messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

	<div><%= f.label :title %><br />
	<%= f.text_field :title %></div>

	<div>File<br />
	<%= f.file_field :data %></div>	

	<div><%= f.submit "Upload" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MainApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
	<nav>
		<ul>
				<li id="nav-logo">
				<%= link_to 'Logo Placeholder', '#' %>
				</li>
		</ul>
		<ul class="pull-right">
			<% if user_signed_in? %>
				<% if current_user.display_name == nil %>
					<li><%= current_user.email %></li>
				<% else %>
					<li><%= current_user.display_name %></li>
				<% end %>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Upload', upload_path %></li>
				<li><%= link_to 'Settings', edit_user_registration_path  %></li>
				<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Sign In', new_user_session_path %></li>
				<li><%= link_to 'Register', new_user_registration_path %></li>
			<% end %>
		</ul>
	</nav>	
</div>

<container id="page_content_container">
<%= yield %>
</container>
</body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>

<%= image_tag current_user.profile_picture.url(:medium) %>
<% current_user.images.each do |img| %>
	<div><%= image_tag img.data.url(:thumb) %><br />
	<p><%= img.title %></p>
	</div>
<% end %>